// frontend/src/utils/currencyCountries.js
const CurrencyCountries = [
  { currencySign: "USD", country: "United States", symbol: "$" },
  { currencySign: "AED", country: "United Arab Emirates", symbol: "د.إ" },
  { currencySign: "AFN", country: "Afghanistan", symbol: "؋" },
  { currencySign: "ALL", country: "Albania", symbol: "L" },
  { currencySign: "AMD", country: "Armenia", symbol: "֏" },
  { currencySign: "ARS", country: "Argentina", symbol: "$" },
  { currencySign: "AUD", country: "Australia", symbol: "A$" },
  { currencySign: "AWG", country: "Aruba", symbol: "ƒ" },
  { currencySign: "AZN", country: "Azerbaijan", symbol: "₼" },
  { currencySign: "BAM", country: "Bosnia and Herzegovina", symbol: "KM" },
  { currencySign: "BBD", country: "Barbados", symbol: "B$" },
  { currencySign: "BDT", country: "Bangladesh", symbol: "৳" },
  { currencySign: "BGN", country: "Bulgaria", symbol: "лв" },
  { currencySign: "BHD", country: "Bahrain", symbol: ".د.ب" },
  { currencySign: "BIF", country: "Burundi", symbol: "FBu" },
  { currencySign: "BMD", country: "Bermuda", symbol: "$" },
  { currencySign: "BND", country: "Brunei", symbol: "B$" },
  { currencySign: "BOB", country: "Bolivia", symbol: "Bs." },
  { currencySign: "BRL", country: "Brazil", symbol: "R$" },
  { currencySign: "BSD", country: "Bahamas", symbol: "B$" },
  { currencySign: "BTN", country: "Bhutan", symbol: "Nu." },
  { currencySign: "BWP", country: "Botswana", symbol: "P" },
  { currencySign: "BYN", country: "Belarus", symbol: "Br" },
  { currencySign: "BZD", country: "Belize", symbol: "BZ$" },
  { currencySign: "CAD", country: "Canada", symbol: "CA$" },
  {
    currencySign: "CDF",
    country: "Democratic Republic of the Congo",
    symbol: "FC",
  },
  { currencySign: "CHF", country: "Switzerland", symbol: "Fr" },
  { currencySign: "CLP", country: "Chile", symbol: "$" },
  { currencySign: "CNY", country: "China", symbol: "¥" },
  { currencySign: "COP", country: "Colombia", symbol: "$" },
  { currencySign: "CRC", country: "Costa Rica", symbol: "₡" },
  { currencySign: "CUP", country: "Cuba", symbol: "$" },
  { currencySign: "CZK", country: "Czech Republic", symbol: "Kč" },
  { currencySign: "DKK", country: "Denmark", symbol: "kr" },
  { currencySign: "DZD", country: "Algeria", symbol: "د.ج" },
  { currencySign: "EGP", country: "Egypt", symbol: "E£" },
  { currencySign: "EUR", country: "Eurozone", symbol: "€" },
  { currencySign: "FJD", country: "Fiji", symbol: "FJ$" },
  { currencySign: "GBP", country: "United Kingdom", symbol: "£" },
  { currencySign: "GEL", country: "Georgia", symbol: "₾" },
  { currencySign: "GHS", country: "Ghana", symbol: "GH₵" },
  { currencySign: "GMD", country: "Gambia", symbol: "D" },
  { currencySign: "GNF", country: "Guinea", symbol: "FG" },
  { currencySign: "GTQ", country: "Guatemala", symbol: "Q" },
  { currencySign: "GYD", country: "Guyana", symbol: "G$" },
  { currencySign: "HKD", country: "Hong Kong", symbol: "HK$" },
  { currencySign: "HNL", country: "Honduras", symbol: "L" },
  { currencySign: "HRK", country: "Croatia", symbol: "kn" },
  { currencySign: "HUF", country: "Hungary", symbol: "Ft" },
  { currencySign: "IDR", country: "Indonesia", symbol: "Rp" },
  { currencySign: "INR", country: "India", symbol: "₹" },
  { currencySign: "IQD", country: "Iraq", symbol: "ع.د" },
  { currencySign: "IRR", country: "Iran", symbol: "﷼" },
  { currencySign: "ISK", country: "Iceland", symbol: "kr" },
  { currencySign: "JMD", country: "Jamaica", symbol: "J$" },
  { currencySign: "JOD", country: "Jordan", symbol: "د.ا" },
  { currencySign: "JPY", country: "Japan", symbol: "¥" },
  { currencySign: "KES", country: "Kenya", symbol: "KSh" },
  { currencySign: "KRW", country: "South Korea", symbol: "₩" },
  { currencySign: "KWD", country: "Kuwait", symbol: "د.ك" },
  { currencySign: "LAK", country: "Laos", symbol: "₭" },
  { currencySign: "LBP", country: "Lebanon", symbol: "ل.ل" },
  { currencySign: "LKR", country: "Sri Lanka", symbol: "Rs" },
  { currencySign: "LSL", country: "Lesotho", symbol: "L" },
  { currencySign: "LYD", country: "Libya", symbol: "ل.د" },
  { currencySign: "MAD", country: "Morocco", symbol: "د.م" },
  { currencySign: "MDL", country: "Moldova", symbol: "L" },
  { currencySign: "MGA", country: "Madagascar", symbol: "Ar" },
  { currencySign: "MKD", country: "North Macedonia", symbol: "ден" },
  { currencySign: "MMK", country: "Myanmar", symbol: "K" },
  { currencySign: "MNT", country: "Mongolia", symbol: "₮" },
  { currencySign: "MOP", country: "Macau", symbol: "MOP$" },
  { currencySign: "MUR", country: "Mauritius", symbol: "₨" },
  { currencySign: "MWK", country: "Malawi", symbol: "MK" },
  { currencySign: "MXN", country: "Mexico", symbol: "MX$" },
  { currencySign: "MYR", country: "Malaysia", symbol: "RM" },
  { currencySign: "MZN", country: "Mozambique", symbol: "MT" },
  { currencySign: "NAD", country: "Namibia", symbol: "N$" },
  { currencySign: "NGN", country: "Nigeria", symbol: "₦" },
  { currencySign: "NOK", country: "Norway", symbol: "kr" },
  { currencySign: "NPR", country: "Nepal", symbol: "₨" },
  { currencySign: "NZD", country: "New Zealand", symbol: "NZ$" },
  { currencySign: "OMR", country: "Oman", symbol: "ر.ع." },
  { currencySign: "PEN", country: "Peru", symbol: "S/." },
  { currencySign: "PHP", country: "Philippines", symbol: "₱" },
  { currencySign: "PKR", country: "Pakistan", symbol: "Rs" },
  { currencySign: "PLN", country: "Poland", symbol: "zł" },
  { currencySign: "QAR", country: "Qatar", symbol: "ر.ق" },
  { currencySign: "RON", country: "Romania", symbol: "lei" },
  { currencySign: "RUB", country: "Russia", symbol: "₽" },
  { currencySign: "SAR", country: "Saudi Arabia", symbol: "﷼" },
  { currencySign: "SEK", country: "Sweden", symbol: "kr" },
  { currencySign: "SGD", country: "Singapore", symbol: "S$" },
  { currencySign: "THB", country: "Thailand", symbol: "฿" },
  { currencySign: "TRY", country: "Turkey", symbol: "₺" },
  { currencySign: "TZS", country: "Tanzania", symbol: "TSh" },
  { currencySign: "UAH", country: "Ukraine", symbol: "₴" },
  { currencySign: "UGX", country: "Uganda", symbol: "USh" },
  { currencySign: "UYU", country: "Uruguay", symbol: "$U" },
  { currencySign: "UZS", country: "Uzbekistan", symbol: "soʻm" },
  { currencySign: "VES", country: "Venezuela", symbol: "Bs." },
  { currencySign: "VND", country: "Vietnam", symbol: "₫" },
  { currencySign: "ZAR", country: "South Africa", symbol: "R" },
  { currencySign: "ZMW", country: "Zambia", symbol: "ZK" },
];

// Helper function to get currency by country
const getCurrencyByCountry = (countryName) => {
  const currency = CurrencyCountries.find((c) => c.country === countryName);
  return currency || CurrencyCountries[0]; // Default to USD
};

// Helper function to format currency
const formatCurrency = (amount, symbol) => {
  return `${symbol}${parseFloat(amount || 0).toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
};

module.exports = { CurrencyCountries, getCurrencyByCountry, formatCurrency };
